export const affirmationPool: string[] = [
  "I am becoming someone who chooses aligned action.",
  "I gently embody focus and trust my next step.",
  "I am becoming someone who moves with calm strength.",
  "I trust myself to respond with clarity and grace.",
  "I move through life with steady confidence.",
  "I choose progress over perfection.",
  "I am learning to trust my inner guidance.",
  "I take grounded action even when things feel uncertain.",
  "I allow ease to shape my decisions.",
  "I am building a life rooted in intention.",
  "I respond thoughtfully instead of reacting impulsively.",
  "I am becoming someone who honors their energy.",
  "I cultivate clarity in every choice I make.",
  "I trust the timing of my growth.",
  "I move forward with quiet determination.",
  "I release what no longer aligns with who I am becoming.",
  "I choose courage over comfort.",
  "I am steady even when circumstances shift.",
  "I embody resilience and softness at the same time.",
  "I give myself permission to grow at my own pace.",
  "I welcome aligned opportunities into my life.",
  "I am grounded in who I am becoming.",
  "I act with intention and purpose.",
  "I choose presence over distraction.",
  "I move with clarity and thoughtful direction.",
  "I trust that each step builds momentum.",
  "I am becoming someone who listens deeply.",
  "I take aligned action without overthinking.",
  "I am calm and capable in every situation.",
  "I honor my boundaries with confidence.",
  "I respond with patience and understanding.",
  "I am learning to move with ease.",
  "I choose thoughtful growth every day.",
  "I trust my ability to navigate change.",
  "I embody quiet confidence.",
  "I allow my actions to reflect my values.",
  "I move forward even when progress feels slow.",
  "I am becoming someone who chooses clarity over chaos.",
  "I trust myself to figure things out.",
  "I align my habits with my highest intentions.",
  "I choose focus over distraction.",
  "I move with calm awareness.",
  "I am grounded in my purpose.",
  "I embody strength with compassion.",
  "I take action that reflects who I want to become.",
  "I allow myself to grow without pressure.",
  "I trust the direction my life is unfolding.",
  "I choose balance in my decisions.",
  "I am becoming someone who trusts deeply.",
  "I move with intention and steadiness.",
  "I release hesitation and take thoughtful steps.",
  "I am capable of meaningful progress.",
  "I choose clarity in my thoughts and actions.",
  "I move through uncertainty with calm presence.",
  "I embody discipline with kindness.",
  "I trust that I am evolving in the right direction.",
  "I align my daily actions with my long-term vision.",
  "I choose peace over pressure.",
  "I am becoming someone who moves with purpose.",
  "I respond with awareness and strength.",
  "I trust myself to make aligned choices.",
  "I allow my growth to unfold naturally.",
  "I choose consistency over intensity.",
  "I embody focus in each moment.",
  "I am calm and intentional in my actions.",
  "I welcome clarity into my decisions.",
  "I trust the process of becoming.",
  "I move with quiet assurance.",
  "I choose actions that reflect my integrity.",
  "I am becoming someone who acts with courage.",
  "I allow space for reflection and growth.",
  "I move forward with thoughtful energy.",
  "I trust my instincts and refine them daily.",
  "I embody grounded confidence.",
  "I choose alignment over impulse.",
  "I take responsibility for my progress.",
  "I am steady in pursuit of what matters.",
  "I move with patience and clarity.",
  "I trust that small steps create lasting change.",
  "I embody calm strength in all I do.",
  "I choose actions that support my future self.",
  "I move through challenges with resilience.",
  "I trust myself to adapt wisely.",
  "I am becoming someone who honors commitment.",
  "I align my thoughts with constructive action.",
  "I move with focus and gentle determination.",
  "I choose awareness in every interaction.",
  "I embody growth through consistent effort.",
  "I trust that I am capable of steady progress.",
  "I respond with clarity instead of confusion.",
  "I choose thoughtful momentum.",
  "I move with balanced intention.",
  "I trust my path and refine it daily.",
  "I embody presence and direction.",
  "I take aligned action without force.",
  "I am becoming someone who moves with purpose and calm.",
  "I choose steady growth over sudden bursts.",
  "I trust myself to stay aligned.",
  "I move forward with clear intention.",
  "I embody the discipline required for my evolution."
];

export function getRandomAffirmation(): string {
  const index = Math.floor(Math.random() * affirmationPool.length);
  return affirmationPool[index];
}

export function getRandomAffirmationExcluding(excluded: string[]): string {
  const filtered = affirmationPool.filter(a => !excluded.includes(a));
  const pool = filtered.length > 0 ? filtered : affirmationPool;
  const index = Math.floor(Math.random() * pool.length);
  return pool[index];
}

